### PR TITLE
fix(checkbox): fixed alignment issue

### LINKED ISSUE #1716: checkbox alignment
we are seeing some differences in checkbox alignment compared to figma component
**Figma**
Screenshot 2023-10-17 at 11 28 53 AM
**Blade**
Screenshot 2023-10-17 at 11 30 28 AM

Note: currently checkbox doesn't have flex shrink 0 so if label is long, checkbox shrinks and breaks aspect-ratio - happens in above screenshot (currently added temp workaround by setting flex shrink 0 on checkbox)

### PR DESCRIPTION
**Pull request by Sanketmundada**
Fixes #1716 

### Changes: 
Removed alignItem `center`, allowing it to default to`flex-start`

### Screenshot:
Screenshot 2023-10-21 at 10 39 36 AM

### CODE REVIEW

**Review by saurabhdaware — DISMISSED** [review]
Looks good to me. Thanks for the PR 🥳 

@anuraghazra can you do L2?

**Comment by saurabhdaware** [comment]
@Sanketmundada can you update the snapshots in the PR? that will make tests pass.

You can run `yarn test:react -u` and `yarn test:react-native -u`

**Comment by anuraghazra** [comment]
@Sanketmundada thanks for the PR. 

There is another small bug with this, on small screen sizes the checkbox icon is getting shrinked: 
image


Can you add `flexShrink: 0` in [here](https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Checkbox/CheckboxIcon/CheckboxIconWrapperStyles.ts#L30)?

**Review by anuraghazra — APPROVED** [review]

**Review by anuraghazra — APPROVED** [review]

**Comment by saurabhdaware** [comment]
Congrats on your PR merge @Sanketmundada 🎉 Make sure to fill the form from "How to sign up" section on https://opensource.razorpay.com/hacktoberfest-2023/ for exciting goodies 🥳

**Comment by Sanketmundada** [comment]
Thanks @saurabhdaware!

**Pull request merged**
