### PR TITLE
chore: move examples inside packages

### PR DESCRIPTION
**Pull request by kamleshchandnani**
This PR does 2 things
* Removes CardWithTokens from recipes as its no longer required since we have better recipes now
* move examples directory under packages for easy discovery and if we want to link with our current version of Blade locally then we can add it to workspace and it'll help us with that

### CODE REVIEW

**Review by anuraghazra — APPROVED** [review]

**Comment by kamleshchandnani** [comment]
@divyanshu013 didn't do that now. because again the hoisting and everything will kick in and might mess up things and will restrict our ability to do experimentation with examples

**Review by divyanshu013 — APPROVED** [review]
Looks good to me.

**Comment by anuraghazra** [comment]
What's pending in this? 🤔

**Comment by divyanshu013** [comment]
Looks good to merge @kamleshchandnani

**Review by cseas — COMMENTED** [review]
I didn't understand the motivation behind this. How does moving examples to a subdirectory help discovery? It actually hurts discovery.

All popular I'm familiar with that provide examples have them at the root level:
- Next.js: https://github.com/vercel/next.js
- Redux: https://github.com/reduxjs/redux

Adding it under `packages/` makes it even more confusing to read the project structure because the general assumption is that every directory under `packages/` is an actual individual package.

**Review by cseas — COMMENTED** [review]
> move examples directory under packages for easy discovery

I didn't understand the motivation behind this. How does moving examples to a subdirectory help discovery? It actually hurts discovery.

All popular projects I'm familiar with that provide examples have them at the root level:
- Next.js: https://github.com/vercel/next.js
- Redux: https://github.com/reduxjs/redux

Adding it under `packages/` makes it even more confusing to read the project structure because the general assumption is that every directory under `packages/` is supposed to be an individually published package.

**Pull request merged**
