### PR TITLE
feat(Typography): expose color from other typography components

### PR DESCRIPTION
**Pull request by saurabhdaware**
We already exposed `color` prop from Text. This PR also exposes it from `Heading`, `Title`, and `Code` component.

### CODE REVIEW

**Comment by saurabhdaware** [comment]
> Check on figma how these tokens are looking? Are they also like surface.text.subtle... for custom colors? Basically we should have same terminology to make it easy to copy the color values.

Checked. It won't be exact dot notation. Will be `/` like we see while building components. Saurav said it will be an overkill. Thread - https://razorpay.slack.com/archives/G01B3LQ9H0W/p1685435890916149

**Review by anuraghazra — DISMISSED** [review]
Looks good to me: 

TODO: 

- [x] Add Snapshot tests (web+native)
- [x] Add storybook examples with the color prop so that we get chromatic snapshots

**Comment by saurabhdaware** [comment]
> Check on figma how these tokens are looking? Are they also like surface.text.subtle... for custom colors? Basically we should have same terminology to make it easy to copy the color values.

This is how it will look on figma @divyanshu013 

https://razorpay.slack.com/archives/G01B3LQ9H0W/p1685521684101769?thread_ts=1685435890.916149&cid=G01B3LQ9H0W

**Review by anuraghazra — APPROVED** [review]

**Comment by saurabhdaware** [comment]
Ignore the color changes on `Code` component, they are fixed in #1240

**Review by divyanshu013 — APPROVED** [review]
Looks good to me.

**Pull request merged**
