### PR TITLE
fix: Request to update twitter to x icon [Fixes #2371]

### LINKED ISSUE #2371: Request to update twitter to x icon in the blade ui library
The Twitter logo has been changed and hasn't been updated on this site.

Steps to Reproduce
Step 1: Go to the url https://blade.razorpay.com/?path=/story/components-icons--all-icons and see twitter old lcon

Screenshot 2024-10-05 at 1 23 46 AM

Expected Behavior
The Twitter logo should be changed to X.

### PR DESCRIPTION
**Pull request by sarthak-kumar-shailendra**
## Description

The Twitter logo has been changed and hasn't been updated on this site. [Fixes #2371]

## Changes

Old icon
Screenshot 2024-10-05 at 1 23 46 AM

New icon
Screenshot 2024-10-05 at 1 26 07 AM

## Component Checklist

- [ ] Update Component Status Page
- [ ] Perform Manual Testing in Other Browsers
- [ ] Add KitchenSink Story
- [ ] Add Interaction Tests (if applicable)
- [ ] Add changeset

### CODE REVIEW

**Comment by sarthak-kumar-shailendra** [comment]
@saurabhdaware Kindly review the changes

**Comment by saurabhdaware** [comment]
Thanks for the PR. I'll get it reviewed from our design team and get back

**Comment by saurabhdaware** [comment]
Meanwhile 
- can you add changeset (you can click the link in changeset comment)
- Update snapshots (You can locally run `yarn test:react -u` and `yarn test:react-native -u` and commit changes)

**Comment by saurabhdaware** [comment]
Hey @sarthak-kumar-shailendra , I got it reviewed from design team but this icon doesn't match the design guidelines we have set for icons. To follow consistency with other icons, we have certain roundness and boldness that is defined in our design icon guidelines.

We also have an automated script to sync figma design icons with code so this change will be done by our design team based on our design guideline and later the automated script will create the PR to add it to icons.

Thanks for the effort and for creating the issue though. We'll keep your issue open and close it when we fix it with automated script.

I see you've also created the other PR for documentation's UI fix which seems good to me. I have suggested one small change. We can merge that one.

**Pull request closed without merging**
