### PR TITLE
feat: update to use focus-visible

### PR DESCRIPTION
**Pull request by anuraghazra**

### CODE REVIEW

**Review by saurabhdaware — DISMISSED** [review]
Nice! Things are looking good now 🎉 

TODO:
- [ ] add changeset

**Review by kamleshchandnani — DISMISSED** [review]
Lets go 🚀

**Comment by kamleshchandnani** [comment]
@anuraghazra resolve conflcts

**Comment by anuraghazra** [comment]
Wow so many conflicts.

**Review by kamleshchandnani — APPROVED** [review]

**Pull request merged**
