### PR TITLE
docs: update blade package and general pages

### PR DESCRIPTION
**Pull request by michizhou**
Update `blade` package and general documentation pages with minor fixes for typos and grammatical mistakes.

### CODE REVIEW

**Review by divyanshu013 — COMMENTED** [review]
Could you please update the PR to only cover spell corrections? Other things are fine as they are now for example - `usecase` is fine

**Comment by divyanshu013** [comment]
Both usecase and use case are fine to keep actually so we can keep the existing spellings as they were initially

**Comment by divyanshu013** [comment]
Yes, in short all changes to usecases or use cases are not needed

**Comment by michizhou** [comment]
@divyanshu013 I've reverted all changes to usecases or use cases. Please let me know if additional changes are needed.

**Review by anuraghazra — APPROVED** [review]

**Review by kamleshchandnani — APPROVED** [review]
LGTM 🚢

**Review by divyanshu013 — APPROVED** [review]
Looks good to me.

**Pull request merged**
