### PR TITLE
build(blade): update version

### PR DESCRIPTION
**Pull request by rzpcibot**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
### Patch Changes

-   6866289: build: fix storybook native failing due to reanimated

### CODE REVIEW

**Review by chaitanyadeorukhkar — APPROVED** [review]

**Review by dhruvdutt — DISMISSED** [review]

**Comment by kamleshchandnani** [comment]
why do we need this to release a version? this is for storybook which is not related to consumer right? and for consumers they'll anyways have to install reanimated as it's marked as externals?

**Comment by anuraghazra** [comment]
We don't transform with babel before bundling? If so then we have to add a migration guide here to let consumers know they  need that babel plugin, else we are fine.

**Comment by chaitanyadeorukhkar** [comment]
Don't need to release this. I'll raise a seperate PR for updating usage docs to add a note about react native reanimated perquisites

**Comment by chaitanyadeorukhkar** [comment]
https://github.com/razorpay/blade/pull/459
https://github.com/razorpay/blade/pull/458

**Comment by kamleshchandnani** [comment]
then shall we close this?

**Pull request closed without merging**
