### PR TITLE
fix: speed up stackblitz

### PR DESCRIPTION
**Pull request by saurabhdaware**
## Description

Speeds up stackblitz examples 

## Changes

- Move from node template to javascript template of stackblitz as it support autocomplete now
- Remove typescript from our examples as it throws runtime errors in javascript template

### CODE REVIEW

**Review by tewarig — COMMENTED** [review]
I tried running fix/broken-stackblitz locally, and everything seems to work fine. However, in the Storybook preview URL, it always shows the error: Can't find packages: react, react-dom, @razorpay/blade.  Could you please check onces  🤔 
Also, can we update the StackBlitz SDK to version 1.11.0? Currently, we are using version 1.9.0.
Everything else seems fine to me.

**Comment by saurabhdaware** [comment]
The installation not working in PRs seem to be some issue with codesandbox package registry. I am unable to access it outside of stackblitz either

image

**Comment by tewarig** [comment]
> razorpay/blade: basic

working now

**Comment by saurabhdaware** [comment]
I added a check to ensure it only adds import if code doesn't have `import React` already.

> Additionally, we need to verify that React is not being imported unnecessarily in other examples.

We need it in every example actually because this is a `javascript` template and requires React to compile JSX

**Review by tewarig — APPROVED** [review]

**Pull request merged**
