### PR TITLE
fix(AutoComplete): hide ActionListSection when items are filtered out

### LINKED ISSUE #1668: Autocomplete: hide ActionListSection if none of the corresponding ActionListItem are filtered as part of search
- In case Autocomplete has multiple `ActionListSection` the title is getting rendered regardless of `ActionListItem` being filtered as the part of search.
- Ideally ActionListSection should be hidden if none of the items are filtered.
- [Slack](https://razorpay.slack.com/archives/CMQ3RBHEU/p1695311173114729?thread_ts=1695293795.816089&cid=CMQ3RBHEU), [Sandbox](https://codesandbox.io/s/prod-paper-d4mn4h?file=/App.tsx)

image

### PR DESCRIPTION
**Pull request by saurabhdaware**
Fixes #1668

### CODE REVIEW

**Review by anuraghazra — DISMISSED** [review]
Looks good, maybe let's add a snapshot test.

**Comment by saurabhdaware** [comment]
> maybe let's add a snapshot test.

Its a bit tricky. For it to be a meaninful snapshot, we will have to open AutoComplete, type something, then snapshot it. (These tests are bit flaky because id keeps changing randomly on CI but not on local). 

Might have to wait for E2E only 🥲

**Comment by anuraghazra** [comment]
Okay, i hope atleast we have chromatic snapshots

**Comment by saurabhdaware** [comment]
> Okay, i hope atleast we have chromatic snapshots

Chromatic snapshots have the same problem too. Chromatic snapshots are taken with autocomplete closed so this particular scenario is not really covered anywhere.

**Review by anuraghazra — APPROVED** [review]

**Pull request merged**
