### PR TITLE
feat(blade): scroll into view tab items when value changes

### PR DESCRIPTION
**Pull request by anuraghazra**
fixes https://github.com/razorpay/blade/issues/1857

### CODE REVIEW

**Review by saurabhdaware — APPROVED** [review]
Looks good to me

**Comment by saurabhdaware** [comment]
On docs page, the tabs are always visible on top. Can you keep a note of this somewhere and fix it? we can merge this PR to unblock acquisition.

image

**Comment by saurabhdaware** [comment]
Should clicking on Tab scroll you to that page in documentation example?

**Comment by anuraghazra** [comment]
> Should clicking on Tab scroll you to that page in documentation example?

No the consumer can handle that via onCLick

**Comment by anuraghazra** [comment]
> On docs page, the tabs are always visible on top. Can you keep a note of this somewhere and fix it? we can merge this PR to unblock acquisition.

Fixed.

**Comment by saurabhdaware** [comment]
@anuraghazra do we still want this PR? Looks a bit outdated now

**Pull request closed without merging**
