### PR TITLE
chore: fix dependabot alerts

### PR DESCRIPTION
**Pull request by anuraghazra**
ran https://www.npmjs.com/package/yarn-audit-fix since yarn doesn't support --fix

### CODE REVIEW

**Review by divyanshu013 — COMMENTED** [review]
Would also need a patch release.

**Comment by kamleshchandnani** [comment]
@divyanshu013 why would this need a patch release? this just has changed things at this project's level right?

**Comment by divyanshu013** [comment]
Wouldn't these also show as transitive deps for blade consumers 🤔

**Comment by anuraghazra** [comment]
Adding the patch changelog then, Yes I think it's safer, If something breaks atleast people won't scratch their head trying to figure out "what changed???"

**Review by divyanshu013 — APPROVED** [review]
Looks good to me.

**Pull request merged**
