### PR TITLE
test: add breadcrumb tests

### PR DESCRIPTION
**Pull request by anuraghazra**
## Component Checklist

- [ ] Update Component Status Page
- [ ] Perform Manual Testing in Other Browsers
- [ ] Add KitchenSink Story
- [ ] Add Interaction Tests (if applicable)
- [ ] Add changeset

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
LGTM. I thought we were writing only E2E tests for new components.

**Review by snitin315 — COMMENTED** [review]
When clicking show code it's not showing the code actual code but just the `<RouterExample />`

Screenshot 2024-02-22 at 5 19 44 PM

**Comment by anuraghazra** [comment]
I'll add codesandbox link

**Review by saurabhdaware — APPROVED** [review]
Looks good to me. No E2E needed?

**Comment by anuraghazra** [comment]
> No E2E needed?

Nope, nothing to test.

**Pull request merged**
