### PR TITLE
feat(checkbox): update small size

### PR DESCRIPTION
**Pull request by nidhi-tandon**
Slack Discussion: https://razorpay.slack.com/archives/CTM086NSF/p1603175140267000?thread_ts=1602750753.212400&cid=CTM086NSF

### CODE REVIEW

**Review by divyanshu013 — COMMENTED** [review]
So `medium` and `small` represent same thing?

**Comment by nidhi-tandon** [comment]
> So `medium` and `small` represent same thing?
The checkbox size for medium and small is same but the text font size differs.

**Review by divyanshu013 — APPROVED** [review]
Looks good to me. Would be good to get one more review.

**Review by dhruvdutt — COMMENTED** [review]
Confirm with app team and designers before merging.

**Comment by shridhar52war** [comment]
We are not using a small-sized checkbox anywhere in the app for now. Need to re-look at the changes in the design.

**Pull request merged**
